# Site settings
language:               "español"
title:                  "lasaspiradoras"
description:            "Estas buscando una aspiradora? te resulta dificil elegir? Aqui estamos para ayudarte. recopilamos las mejores aspiradoras del mercado para ayudarte a elegir la que mas se adapte a tus necesidades"
google-verification:    ""
url: ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"
  - "/assets/"

exclude:
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname
