# Site settings
language:               "español"
title:                  "lasaspiradoras"
description:            "Estas buscando una aspiradora? te resulta dificil elegir? Aqui estamos para ayudarte. recopilamos las mejores aspiradoras del mercado para ayudarte a elegir la que mas se adapte a tus necesidades"
google-verification:    ""
url: "http://www.lasaspiradoras.com"

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5
